### ISSUE TITLE
Unable to specify editor's arguments at configuration file

### ISSUE THREAD

**Issue by illia-danko** [clearloop/leetcode-cli#111]
Use case:
As a user I want to use my editor (nvim) without any plugins and configuration to have a clean and similar to white board code interview experience. Neovim has `--clean` argument for this purpose  (see nvim --help).

It seems that existing ~/.leetcode/leetcode.toml doesn't have this possibility to teach leetcode-cli to run editor with arguments.

if the code block section is modified to something like:

```toml
[code]
editor = "nvim --clean"
lang = "golang"
pick = "${fid}.${slug}"
submission = "${fid}.${slug}.${sid}.${ac}"
```
leetcode-cli command returns: `error: No such file or directory (os error 2), please try again`
