### ISSUE TITLE
leetcode test 1 error

### ISSUE THREAD

**Issue by jiaqiwang969** [clearloop/leetcode-cli#117]
[INFO  leetcode_cli::plugins::leetcode] Sending code to judge...
error: invalid type: sequence, expected a string at line 1 column 221

**Comment by vshlemon** [comment]
I get the same error when doing `leetcode test <id>`

The error seems to be a rust error, I am writing leetcode solutions in python, stored in default .leetcode/code location

The previous language for solutions was rust, which is what I originally pulled the Problems in via. `leetcode list` and `leetcode pick <id>` - only after using `leetcode edit <id>` with Rust as the language, did I switch the language to Python - not sure if this is the cause for the error i.e. submissions for tests are still being sent as Rust ones even though the solution is in Python...

**Comment by choikangjae** [comment]
As [morristai](https://github.com/morristai) [mentioned](https://github.com/clearloop/leetcode-cli/issues/97#issuecomment-1396415219
) earlier,  you can fix that issue with:
```
cargo install --git https://github.com/clearloop/leetcode-cli
```

It will update your `leetcode-cli` with newer version, so don't bother to delete the old version.

And you can make sure the latest version is installed with:
```bash
$ leetcode -V
# result -> leetcode-cli 0.3.12
```

`code` section in `~/.leetcode/leetcode.toml` should look like:
```toml
[code]
editor = "lvim"
lang = "python3"
edit_code_marker = false
comment_problem_desc = false
comment_leading = "///"
start_marker = "@lc code=start"
end_marker = "@lc code=start"
test = true
pick = "${fid}.${slug}"
submission = "${fid}.${slug}.${sid}.${ac}"
```
