### ISSUE TITLE
Running "leetcode edit" with a specified language resets config options

### ISSUE THREAD

**Issue by lukejans** [clearloop/leetcode-cli#187]
I had the following code configuration options in my config file.

```toml
[code]
editor = "cat"
lang = "java"
comment_problem_desc = true
comment_leading = "//"
test = true
```

This was working great but when I decided to use another language using something like `$ leetcode edit 1 -l javascript` I would get the following config file:

```toml
[code]
editor = "cat"
lang = "javascript"
```

after running the command the tool successfully creates a new problem to edit with the previous config options but it also deletes those config options. It keeps only the editor option and updates the lang option with the argument from the previously ran command.
