### ISSUE TITLE
`emacsclient` doesn't works.

### ISSUE THREAD

**Issue by samyak039** [clearloop/leetcode-cli#75]
I am trying to open via `leetcode edit <ID>` command, it is working fine with `vim`, `nvim` & even `emacs` but does not open the file with `emacsclient` it gives error:

```sh
$ leetcode edit 1
error: No such file or directory (os error 2), please try again
```

here's my `leetcode.toml`
```toml
[code]
editor = "emacsclient -n -s doom"             # "nvim" and "emacs" works fine
lang = "cpp"
pick = "${fid}.${slug}"
submission = "${fid}.${slug}.${sid}.${ac}"
```

Note: `emacsclient` is the command to use emacs in daemon-client mode.
